language: php

matrix:
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'

before_install:
  - phpenv config-add travis.ini

install:
  - if [[ $TRAVIS_PHP_VERSION == 5.6 ]] ; then yes | pecl install -f apcu-4.0.11; fi
  - composer install --prefer-dist

before_script:
  - phpenv rehash

script:
  - vendor/bin/phpunit