language: php

matrix:
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'

services:
  - memcached
  - redis-server

before_install:
  - if ! php -m | grep -q 'apc'; then echo yes | pecl install -f apcu-4.0.11; fi
  - phpenv config-add travis.ini

install:
  - composer install --prefer-dist

before_script:
  - phpenv rehash

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)