language: php

matrix:
  include:
    - php: '5.6'
      env: INSTALL_APCU=true
    - php: '7.0'
    - php: '7.1'

before_install:
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - if [[ -v $INSTALL_APCU ]]; then yes | pecl install -f apcu-4.0.11; fi
  - composer install --prefer-dist

before_script:
  - phpenv rehash

script:
  - vendor/bin/phpunit