language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

install:
 - composer install --prefer-dist
 - pyrus install pear/PHP_CodeSniffer

before_script:
  - phpenv rehash

script:
 - vendor/bin/phpunit
 - phpcs src/