language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_install:
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - pecl install -f apcu-4.0.11 || true
  - composer install --prefer-dist

before_script:
  - phpenv rehash

script:
  - vendor/bin/phpunit